runtime: python39

handlers:
  - url: /
    static_files: index.html
    upload: index.html

  - url: /(.*)
    static_files: \1
    upload: (.*)



#runtime: nodejs18

#handlers:
#  - url: /.*
#    script: auto

